import Head from 'next/head'
import { makeStyles } from "@material-ui/core/styles";
import Footer from '../components/Footer';
import Landing from './Home/landing';
import Container from '@material-ui/core/Container';


const useStyles = makeStyles(theme => ({
  background: {
    backgroundColor: '#F2F4F5',
    border: '1px solid red',
    height: '100vh',
    // width: '100vw'
    padding: 0,
    margin: 0,
  }
}));


export default function Home() {
  const styles = useStyles();
  // const isMobile = useMediaQuery(theme => theme.breakpoints.down("sm"));

  return (
    <Container maxWidth="xl" className={styles.background}>
      <Head>
        <title>Simflight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Landing/>

      {/* <Footer/> */}
    </Container>
  )
}
