import Head from 'next/head'
import { makeStyles } from "@material-ui/core/styles";
import Landing from '../src/components/Landing';
import Container from '@material-ui/core/Container';
import { useMediaQuery } from "@material-ui/core";
import WhatWeDo from '../src/components/WhatWeDo';

const useStyles = makeStyles(theme => ({
  container: {
    // border: '1px solid red',
    // height: '100vh',
    // minHeight: 'calc(100vh - 170px)',
    padding: 0,
    [theme.breakpoints.down('sm')]: {
      marginTop: 50
    }
  }
}));

export default function Home() {
  const styles = useStyles();
  const isMobile = useMediaQuery(theme => theme.breakpoints.down("sm"));
  const isLaptop = useMediaQuery(theme => theme.breakpoints.down("md"));

  return (
    <Container maxWidth={isMobile ? 'sm' : isLaptop ? 'md' : 'lg'} className={styles.container}>
      <Head>
        <title>Simflight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Landing/>
      <WhatWeDo/>
    </Container>
  )
}
