import Head from 'next/head'
import { makeStyles } from "@material-ui/core/styles";
import Footer from '../src/components/Footer';
import Landing from './Home/landing';
import Container from '@material-ui/core/Container';
import { useMediaQuery } from "@material-ui/core";

const useStyles = makeStyles(theme => ({
  container: {
    backgroundColor: '#F2F4F5',
    // border: '1px solid red',
    // height: '100vh',
    // minHeight: 'calc(100vh - 170px)',
    padding: 0,
  }
}));

export default function Home() {
  const styles = useStyles();
  const isMobile = useMediaQuery(theme => theme.breakpoints.down("sm"));

  return (
    <Container maxWidth={isMobile ? 'xs' : 'lg'} className={styles.container}>
      <Head>
        <title>Simflight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Landing/>
      
    </Container>
  )
}
