import Head from 'next/head'
import { makeStyles } from "@material-ui/core/styles";
import Landing from '../src/components/Landing';
import Container from '@material-ui/core/Container';
import { useMediaQuery } from "@material-ui/core";
import WhatWeDo from '../src/components/WhatWeDo';
import HeadMeta from '../src/components/Head';
import { getStaticPropsForTina, staticRequest } from "tinacms";

const useStyles = makeStyles(theme => ({
  container: {
    // border: '1px solid red',
    // height: '100vh',
    // minHeight: 'calc(100vh - 170px)',
    padding: 0,
    [theme.breakpoints.down('sm')]: {
      marginTop: 50
    }
  }
}));

export default function Home(props) {
  const classes = useStyles();
  const isMobile = useMediaQuery(theme => theme.breakpoints.down("sm"));
  const isLaptop = useMediaQuery(theme => theme.breakpoints.down("md"));


  return (
    <Container maxWidth={isMobile ? 'sm' : isLaptop ? 'md' : 'lg'} className={classes.container}>
      <HeadMeta homepage="true" title="Simflight" description="Generated by create next app" icon="/favicon.ico" />

      <Landing {...props.data.getPagesDocument.data.blocks[0]} />
      <WhatWeDo {...props.data.getPagesDocument.data.blocks[1]} />
    </Container>
  )
}

export const getStaticProps = async () => {
  const tinaProps = (await getStaticPropsForTina({
    query: `#graphql
    query ContentQuery($relativePath: String!) {
      getPagesDocument(relativePath: $relativePath) {
        data {
          __typename
          blocks {
            __typename
            ... on PagesBlocksHero {
              tagline
              headline
              text
              actions {
                label
                type
                icon
                link
              }
              color
              image {
                src
                alt
              }
            }

            ... on PagesBlocksFeatures {
              items {
                title
                text {
                  item1
                  item2
                  item3
                }
                image {
                  src
                  alt
                }
              }
            }
          }
        }
      }
    }
  `,
  variables: {relativePath: "homepage.md"},
  }))

  return {
    props: {
      ...tinaProps,
    },
  };
};
